project:
  type: website
  output-dir: docs

website:
  title: "Política para no políticos"
  navbar:
    background: "#1a365d"
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Empleo Público"
        href: 01_empleo_publico.qmd

format:
  html:
    theme: flatly
    toc: true